version: "3.7"

services:
  minecraft-server:
    image: minecraft-server:1.14.4
    build: .
    ports:
      - 25565:25565
    volumes:
      - ./world:/server/world:rw
    command:
      - java
      - -Xmx1024M
      - -Xms1024M
      - -jar
      - server.jar
      - nogui
